# Generated by Django 5.2.18 on 2026-10-08 13:08

import crm.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccDoc',
            fields=[
                ('id', models.CharField(default=crm.models._acc_doc_id, max_length=40, primary_key=True, serialize=False)),
                ('counterparty', models.CharField(max_length=300)),
                ('type', models.CharField(default='Акт сверки', max_length=100)),
                ('status', models.CharField(default='requested', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccTask',
            fields=[
                ('id', models.CharField(default=crm.models._acc_task_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('period', models.CharField(default='monthly', max_length=10)),
                ('reporting_period', models.CharField(blank=True, max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('receipt_file', models.CharField(blank=True, max_length=500)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardSettings',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.CharField(default=crm.models._campaign_id, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('channel', models.CharField(default='Instagram', max_length=60)),
                ('status', models.CharField(default='active', max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('leads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.CharField(default=crm.models._content_id, max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=20)),
                ('position', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['type', 'position'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.CharField(default=crm.models._field_def_id, max_length=40, primary_key=True, serialize=False)),
                ('resource', models.CharField(choices=[('task', 'Задачи'), ('client', 'Клиенты'), ('deal', 'Сделки')], max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('select', 'Список'), ('checkbox', 'Флажок'), ('url', 'Ссылка')], default='text', max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['resource', 'position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=60)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=60)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, max_length=200)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.CharField(default=crm.models._account_id, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(blank=True, max_length=60)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TurnkeyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=60)),
                ('sphere', models.CharField(blank=True, max_length=200)),
                ('budget', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('services', models.JSONField(blank=True, default=list)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=20)),
                ('entity_type', models.CharField(db_index=True, max_length=20)),
                ('entity_id', models.CharField(db_index=True, max_length=60)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=crm.models._client_id, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('company', 'Компания'), ('person', 'Физлицо')], default='company', max_length=10)),
                ('status', models.CharField(choices=[('lead', 'Потенциальный'), ('active', 'Активный'), ('paused', 'На паузе'), ('archived', 'Архив')], default='lead', max_length=10)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.CharField(default=crm.models._deal_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('pipeline', models.CharField(default='sales', max_length=20)),
                ('stage', models.CharField(default='lead', max_length=30)),
                ('position', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(choices=[('KGS', 'сом'), ('USD', '$'), ('EUR', '€'), ('RUB', '₽'), ('KZT', '₸')], default='KGS', max_length=3)),
                ('probability', models.PositiveSmallIntegerField(default=20)),
                ('expected_close', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=crm.models._page_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Без названия', max_length=300)),
                ('content', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='crm.deal')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='crm.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Директор'), ('manager', 'Управляющий'), ('marketer', 'Маркетолог'), ('smm', 'СММ-специалист'), ('accountant', 'Бухгалтер'), ('finance', 'Финансист')], max_length=20)),
                ('resource', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=40)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('role', 'resource', 'field')},
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.CharField(default=crm.models._idea_id, max_length=40, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=150)),
                ('author_role', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('task', 'Задача'), ('deal', 'Сделка'), ('lead', 'Заявка'), ('mention', 'Упоминание'), ('system', 'Система')], default='system', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10)),
                ('link_type', models.CharField(blank=True, max_length=20)),
                ('link_id', models.CharField(blank=True, max_length=60)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('delivered', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(default=crm.models._payment_id, max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('direction', models.CharField(choices=[('in', 'Поступление'), ('out', 'Расход')], default='in', max_length=3)),
                ('kind', models.CharField(choices=[('payment', 'Оплата клиента'), ('commission', 'Комиссия'), ('investment', 'Инвестиция'), ('payout', 'Выплата'), ('expense', 'Расход'), ('refund', 'Возврат')], default='payment', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.deal')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Директор'), ('manager', 'Управляющий'), ('marketer', 'Маркетолог'), ('smm', 'СММ-специалист'), ('accountant', 'Бухгалтер'), ('finance', 'Финансист')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('telegram_chat_id', models.CharField(blank=True, max_length=40)),
                ('notify_telegram', models.BooleanField(default=True)),
                ('telegram_min_priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10)),
                ('dnd_enabled', models.BooleanField(default=False)),
                ('dnd_start', models.TimeField(default=datetime.time(22, 0))),
                ('dnd_end', models.TimeField(default=datetime.time(8, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
        migrations.CreateModel(
            name='SmmTask',
            fields=[
                ('id', models.CharField(default=crm.models._smm_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('period', models.CharField(default='daily', max_length=10)),
                ('category', models.CharField(default='Контент', max_length=60)),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('due_date', models.CharField(blank=True, max_length=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_by_login', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarPost',
            fields=[
                ('id', models.CharField(default=crm.models._post_id, max_length=40, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(default='post', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='idea', max_length=30)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='crm.socialaccount')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(default=crm.models._task_id, max_length=40, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('assignee', models.CharField(blank=True, db_index=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(default='normal', max_length=10)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('review', 'На проверке'), ('done', 'Выполнена'), ('rejected', 'Отклонена')], default='new', max_length=20)),
                ('result_text', models.TextField(blank=True)),
                ('result_link', models.CharField(blank=True, max_length=500)),
                ('rejection_reason', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('content', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_by_login', models.CharField(blank=True, max_length=150)),
                ('created_by_name', models.CharField(blank=True, max_length=150)),
                ('created_by_role', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('by_name', models.CharField(max_length=150)),
                ('by_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.task')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['pipeline', 'stage'], name='crm_deal_pipelin_f251db_idx'),
        ),
    ]
